# Generated by Django 6.0 on 2025-12-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
